# enable zmk studio for realtime keymap updates
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# 우분투 블루투스 끊김 해결 설정 (새로 추가한 부분)
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# 마우스 키 활성화
CONFIG_ZMK_MOUSE=y

# (선택) 마우스 속도 조정
CONFIG_ZMK_MOUSE_TICK_DURATION=8
CONFIG_ZMK_MOUSE_SMOOTH_SCROLLING=y
